/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

/**
 *
 * @author myoss
 */
public class Teamleader extends javax.swing.JFrame {

    /**
     * Creates new form Teamleader
     */
    public Teamleader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        prograss = new javax.swing.JButton();
        Assigntask = new javax.swing.JButton();
        ctask = new javax.swing.JButton();
        assproject = new javax.swing.JButton();
        Vaction = new javax.swing.JButton();
        report = new javax.swing.JButton();
        Penalties = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setPreferredSize(new java.awt.Dimension(652, 452));
        setResizable(false);
        setSize(new java.awt.Dimension(651, 651));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Team Leader");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, -10, 240, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\myoss\\Downloads\\icon\\Supervisor-icon.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 100, 160, 200);

        prograss.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prograss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/prograss.png"))); // NOI18N
        prograss.setText("Project Prograss");
        prograss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prograssActionPerformed(evt);
            }
        });
        getContentPane().add(prograss);
        prograss.setBounds(40, 310, 270, 40);

        Assigntask.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Assigntask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/tm-assgien task-icon.png"))); // NOI18N
        Assigntask.setText("Assigen tasks");
        Assigntask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssigntaskActionPerformed(evt);
            }
        });
        getContentPane().add(Assigntask);
        Assigntask.setBounds(40, 160, 270, 40);

        ctask.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ctask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/com tasks-icon.png"))); // NOI18N
        ctask.setText("Complete tasks");
        ctask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctaskActionPerformed(evt);
            }
        });
        getContentPane().add(ctask);
        ctask.setBounds(40, 210, 270, 40);

        assproject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assproject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Assproject.png"))); // NOI18N
        assproject.setText("Assigened Projects");
        assproject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assprojectActionPerformed(evt);
            }
        });
        getContentPane().add(assproject);
        assproject.setBounds(40, 260, 270, 40);

        Vaction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Vaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Coffee-break-icon.png"))); // NOI18N
        Vaction.setText("Vactions");
        Vaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VactionActionPerformed(evt);
            }
        });
        getContentPane().add(Vaction);
        Vaction.setBounds(40, 60, 270, 40);

        report.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/report-icon.png"))); // NOI18N
        report.setText("  Reports");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        getContentPane().add(report);
        report.setBounds(40, 360, 270, 40);

        Penalties.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Penalties.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/penlatis.png"))); // NOI18N
        Penalties.setText("Penalties");
        Penalties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenaltiesActionPerformed(evt);
            }
        });
        getContentPane().add(Penalties);
        Penalties.setBounds(40, 110, 270, 40);

        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Exit.png"))); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(440, 350, 160, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/rsz_background.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(650, 450));
        jLabel3.setPreferredSize(new java.awt.Dimension(650, 450));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 650, 449);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void AssigntaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssigntaskActionPerformed
        // TODO add your handling code here:
        Tmassigentask e = new Tmassigentask();
        e.setLocation(400, 200);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AssigntaskActionPerformed

    private void VactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VactionActionPerformed
        // TODO add your handling code here:
        Tmvaction e = new Tmvaction();
        e.setLocation(400, 200);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VactionActionPerformed

    private void PenaltiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenaltiesActionPerformed
        // TODO add your handling code here:
        Tmpenlaties e = new Tmpenlaties();
        e.setLocation(400, 200);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PenaltiesActionPerformed

    private void ctaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctaskActionPerformed
        // TODO add your handling code here:
        Tmcomtasks e = new Tmcomtasks();
        e.setLocation(400, 200);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ctaskActionPerformed

    private void assprojectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assprojectActionPerformed
        // TODO add your handling code here:
        Tmassproject e = new Tmassproject();
        e.setLocation(400, 200);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_assprojectActionPerformed

    private void prograssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prograssActionPerformed
        // TODO add your handling code here:
        Tmprojectprograss e = new Tmprojectprograss();
        e.setLocation(400, 200);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prograssActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        Tmreport e = new Tmreport();
        e.setLocation(400, 200);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teamleader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teamleader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teamleader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teamleader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teamleader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Assigntask;
    private javax.swing.JButton Penalties;
    private javax.swing.JButton Vaction;
    private javax.swing.JButton assproject;
    private javax.swing.JButton ctask;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton prograss;
    private javax.swing.JButton report;
    // End of variables declaration//GEN-END:variables
}
